### Update BiddingStartStatus 
PUT http://localhost:4004/odata/v4/nauticalservice/biddingStartManual('4000000641')
Content-Type: application/json

{
    "Chrnmin" : "4000000631",
    "biddStartStatus" : false
}


######
PUT http://localhost:4004/odata/v4/nauticalservice/BidMasterSet(BidprofileId='TESTING',Bname='',Code='TEST')
Content-Type: application/json

{
     "BidprofileId": "TESTING",
      "Bname": "",
      "Code": "TEST",
      "Value": "Twefghjk",
      "Cvalue": 0,
      "Cunit": "",
      "Datatype": "CHAR",
      "Tablename": "/NAUTI/CLASS",
      "MultiChoice": false
}

#####

DELETE http://localhost:4004/odata/v4/nauticalservice/quotations(Chrnmin='4000000641',Voyno='1000000281',Lifnr='2100000001')


###
POST http://localhost:4004/odata/v4/nauticalservice/ControllerLiveBidDetails
Content-Type: application/json

{
    "createdBy" : "user123",
    "charmin": "400000008",
    "voyno": "100000057",
    "quotationPrice": "1000.00"
}
#####
GET  http://localhost:4004/odata/v4/nauticalservice/biddingStartManual

GET http://localhost:4004/odata/v4/nauticalservice/quotations?$filter=Chrnmin eq '4000000601'


####
POST  http://localhost:4004/odata/v4/nauticalservice/newallstatusesSet
Content-Type: application/json

     {
      "Voyage": "1000000009",
      "Status": "Voyage Appr Pend"
     
    }
###

GET http://localhost:4004/odata/v4/nauticalservice/quotations


###
POST http://localhost:4004/odata/v4/nauticalservice/quotations
Content-Type: application/json

{
  "Lifnr": "2100000002",
  "Voyno": "1000000197",
  "Chrnmin": "4000000601",
  "createdBy":"A.SHARMA",
  "vendorName" : "ESSAR Shipping",
  "Vimono": "ESSAR123",
  "Vname": "ESS87690",
  "Biddate": "2024-07-23",
  "Bidtime": "00:41:16",
  "to_quote_item": [
    {
    "Zcode": "COOR",
    "CodeDesc": "COUNTRY OF ORIGIN",
    "Cunit": "",
    "Cvalue": "0.000",
    "Value": "IN",
    "Zcom": ""
    },
    {
    "Zcode": "DAT1",
    "CodeDesc": "LAST CLEANING DATE",
    "Cunit": "",
    "Cvalue": "0.000",
    "Value": "2024-05-03",
    "Zcom": ""
    },
    {
    "Zcode": "PORT",
    "CodeDesc": "LAST PORT OF CALL",
    "Cunit": "",
    "Cvalue": "0.000",
    "Value": "MUMBAI",
    "Zcom": ""
    },
    {
    "Zcode": "CLASS",
    "CodeDesc": "CLASS OF VESSEL",
    "Cunit": "",
    "Cvalue": "0.000",
    "Value": "A",
    "Zcom": ""
    },
    {
    "Zcode": "DEMURRAGE",
    "CodeDesc": "DEMURRAGE",
    "Cunit": "INR",
    "Cvalue": "0.000",
    "Value": "120000",
    "Zcom": ""
    },
    {
    "Zcode": "FREIG",
    "CodeDesc": "FREIGHT",
    "Cunit": "INR",
    "Cvalue": "0.000",
    "Value": "3000000",
    "Zcom": ""
    }
  ]
}


###
GET http://localhost:4004/odata/v4/nauticalservice/CompareLiveFreight?$filter=Chrnmin eq '4000000001'

###
GET http://localhost:4004/odata/v4/nauticalservice/xNAUTIxbidhist_valuehelp