POST http://localhost:4004/odata/v4/nauticalservice/ControllerLiveBidDetails
Content-Type: application/json

{
    "createdBy" : "user123",
    "charmin": "400000008",
    "voyno": "100000057",
    "quotationPrice": "1000.00"
}
#####

GET http://localhost:4004/odata/v4/nauticalservice/xNAUTIxallstatuses


####
POST  http://localhost:4004/odata/v4/nauticalservice/newallstatusesSet
Content-Type: application/json

     {
      "Voyage": "1000000009",
      "Status": "Voyage Appr Pend"
     
    }